apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: focus-flow-cloud
type: Opaque
data:
  postgres-user: dGVzdFVzZXI=
  postgres-password: dGVzdFBhc3N3b3Jk
  postgres-db: Zm9jdXNfZmxvdw==
