name: Release

on:
  push:
    tags:
      - "v*"
      - "backend-v*"
      - "app-v*"

env:
  CARGO_TERM_COLOR: always

jobs:
  backend-build:
    if: startsWith(github.ref, 'refs/tags/v') || startsWith(github.ref, 'refs/tags/backend-v')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-gnu

      - uses: swatinem/rust-cache@v2
        with:
          workspaces: "backend"

      - name: Build binaries
        run: |
          cargo build --release --target x86_64-unknown-linux-gnu

      - name: Prepare binaries
        run: |
          cp target/x86_64-unknown-linux-gnu/release/focus_flow_cloud ./focus_flow_cloud-amd64

      - name: Upload Binary Artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-bin
          path: backend/focus_flow_cloud-amd64
          if-no-files-found: error

      - name: Extract version from Cargo.toml
        id: crate-version
        uses: colathro/crate-version@2.0.0
        with:
          file: "backend/Cargo.toml"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/focusflowcloud
          tags: |
            type=raw,value=${{ steps.crate-version.outputs.version }}
            type=raw,value=latest
            type=ref,event=tag

      - name: Build and push Docker
        uses: docker/build-push-action@v5
        with:
          context: backend
          file: backend/Dockerfile.production
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          platforms: linux/amd64
          cache-to: type=gha,mode=max

  create-release:
    needs: [backend-build]
    if: always() && (needs.backend-build.result == 'success')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Download Backend Artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-bin

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          generate_release_notes: true
          files: |
            focus_flow_cloud-amd64
